openapi: 3.0.0
info:
  title: Freelance Platform API
  version: 1.0.0

components:
  schemas:
    Account:
      type: object
      properties:
        accountId:
          type: integer
          format: int64
        email:
          type: string
        password:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        avatarUrl:
          type: string
        balance:
          type: number
          format: float
        role:
          type: string
          enum: [CLIENT, FREELANCER]
        isVerified:
          type: boolean
        verifiedAt:
          type: string
          format: date-time
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        active:
          type: boolean

    RefreshToken:
      type: object
      properties:
        refreshTokenId:
          type: integer
          format: int64
        accountId:
          type: integer
          format: int64
        token:
          type: string
        createdAt:
          type: string
          format: date-time
        expiryDate:
          type: string
          format: date-time

    Transaction:
      type: object
      properties:
        transactionId:
          type: integer
          format: int64
        accountId:
          type: integer
          format: int64
        amount:
          type: number
          format: float
        type:
          type: string
          enum: [DEBIT, CREDIT]
        status:
          type: string
          enum: [PENDING, COMPLETED, FAILED]
        createdAt:
          type: string
          format: date-time

    Message:
      type: object
      properties:
        messageId:
          type: integer
          format: int64
        senderId:
          type: integer
          format: int64
        receiverId:
          type: integer
          format: int64
        content:
          type: string
        createdAt:
          type: string
          format: date-time

    JobCategory:
      type: object
      properties:
        jobCategoryId:
          type: integer
          format: int64
        name:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    Job:
      type: object
      properties:
        jobId:
          type: integer
          format: int64
        jobCategoryId:
          type: integer
          format: int64
        clientId:
          type: integer
          format: int64
        title:
          type: string
        description:
          type: string
        minBudget:
          type: number
          format: float
        maxBudget:
          type: number
          format: float
        status:
          type: string
          enum: [OPEN, IN_PROGRESS, COMPLETED, CANCELLED]
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    Milestone:
      type: object
      properties:
        milestoneId:
          type: integer
          format: int64
        jobId:
          type: integer
          format: int64
        title:
          type: string
        budgetRatio:
          type: number
          format: float
        deadline:
          type: string
          format: date-time
        status:
          type: string
          enum: [PENDING, COMPLETED, FAILED]
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    Proposal:
      type: object
      properties:
        proposalId:
          type: integer
          format: int64
        jobId:
          type: integer
          format: int64
        freelancerId:
          type: integer
          format: int64
        budget:
          type: number
          format: float
        deliveryTime:
          type: string
          format: date-time
        status:
          type: string
          enum: [PENDING, ACCEPTED, REJECTED]
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    ProjectFile:
      type: object
      properties:
        projectFileId:
          type: integer
          format: int64
        fileId:
          type: integer
          format: int64
        projectId:
          type: integer
          format: int64
        uploaderId:
          type: integer
          format: int64

    File:
      type: object
      properties:
        fileId:
          type: integer
          format: int64
        fileName:
          type: string
        fileUrl:
          type: string
        fileType:
          type: string
        size:
          type: integer
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    MessageAttachment:
      type: object
      properties:
        messageAttachmentId:
          type: integer
          format: int64
        messageId:
          type: integer
          format: int64
        fileId:
          type: integer
          format: int64

    ProposalAttachment:
      type: object
      properties:
        proposalAttachmentId:
          type: integer
          format: int64
        proposalId:
          type: integer
          format: int64
        fileId:
          type: integer
          format: int64

    ApiResponse:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
    LoginResponse:
      type: object
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            account:
              $ref: '#/components/schemas/Account'

paths:
  /login:
    post:
      summary: Login to an account
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '400':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'