openapi: 3.0.1
info:
  title: Freelance Platform API
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    FileDto:
      $ref: 'model/file.yml#/FileDto'
    MessageDto:
      $ref: 'model/message.yml#/MessageDto'
    MilestoneDto:
      $ref: 'model/milestone.yml#/MilestoneDto'
    ProjectDto:
      $ref: 'model/project.yml#/ProjectDto'
    ProjectCategoryDto:
      $ref: 'model/project-category.yml#/ProjectCategoryDto'
    ProposalDto:
      $ref: 'model/proposal.yml#/ProposalDto'
    RefreshTokenDto:
      $ref: 'model/refresh-token.yml#/RefreshTokenDto'
    TransactionDto:
      $ref: 'model/transaction.yml#/TransactionDto'

paths:
  /auth/login:
    $ref: 'path/auth/login.yml'
  /accounts:
    $ref: 'path/account.yml'
  /accounts/{accountId}:
    $ref: 'path/account-accountId.yml'
  /projects:
    $ref: 'path/project.yml'
  /projects/{projectId}:
    $ref: 'path/project-projectId.yml'
  /projectCategories:
    $ref: 'path/projectCategory.yml'
  /projectCategories/{projectCategoryId}:
    $ref: 'path/projectCategory-projectCategoryId.yml'

