openapi: 3.0.1
info:
  title: Freelance Platform API
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    FileDto:
      $ref: 'model/file.yml#/FileDto'
    MessageDto:
      $ref: 'model/message.yml#/MessageDto'
    MilestoneDto:
      $ref: 'model/milestone.yml#/MilestoneDto'
    ProfileDto:
      $ref: 'model/profile.yml#/ProfileDto'
    ProposalDto:
      $ref: 'model/proposal.yml#/ProposalDto'
    RefreshTokenDto:
      $ref: 'model/refresh-token.yml#/RefreshTokenDto'
    SkillDto:
      $ref: 'model/skill.yml#/SkillDto'
    TransactionDto:
      $ref: 'model/transaction.yml#/TransactionDto'

paths:
  /auth/me:
    $ref: 'path/auth/me.yml'
  /auth/login-with-google:
    $ref: 'path/auth/login-with-google.yml'
  /auth/refresh-token:
    $ref: 'path/auth/refresh-token.yml'
  /auth/login:
    $ref: 'path/auth/login.yml'
  /auth/register:
    $ref: 'path/auth/register.yml'
  /auth/logout:
    $ref: 'path/auth/log-out.yml'
  /auth/forgot-password:
    $ref: 'path/auth/forgot-password.yml'
  /auth/reset-password:
    $ref: 'path/auth/reset-password.yml'
  /accounts:
    $ref: 'path/account.yml'
  /accounts/{accountId}:
    $ref: 'path/account-accountId.yml'
  /projects:
    $ref: 'path/project.yml'
  /projects/{projectId}:
    $ref: 'path/project-projectId.yml'
  /projectCategories:
    $ref: 'path/projectCategory.yml'
  /projectCategories/{projectCategoryId}:
    $ref: 'path/projectCategory-projectCategoryId.yml'
  /profiles:
    $ref: 'path/profile.yml'
  /profiles/{profileId}:
    $ref: 'path/profile-profileId.yml'
  /transactions:
     $ref: 'path/transaction.yml'
  /transactions/{transactionId}:
    $ref: 'path/transaction-transactionId.yml'
  /proposals:
     $ref: 'path/proposal.yml'
  /proposals/{proposalId}:
    $ref: 'path/proposal-proposalId.yml'
  /milestones:
     $ref: 'path/milestone.yml'
  /milestones/{milestoneId}:
    $ref: 'path/milestone-milestoneId.yml'
  /messages:
     $ref: 'path/message.yml'
  /messages/{messagesId}:
    $ref: 'path/message-messageId.yml'   
  /files:
     $ref: 'path/file.yml'
  /files/{fileId}:
    $ref: 'path/file-fileId.yml'   
  /skills:
    $ref: 'path/skill.yml'
  /skills/{skillId}:
    $ref: 'path/skill-skillId.yml'

