openapi: 3.0.1
info:
  title: Freelance Platform API
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /auth/login:
    $ref: 'path/auth/login.yml'
  /account:
    $ref: 'path/account.yml'
  /account/{userId}:
    $ref: 'path/account-accountId.yml'
