get:
  summary: Get a list of projects
  operationId: getProjects
  security:
    - bearerAuth: []
  parameters:
    - $ref: '../param/pageable.yml#/Pageable'
    - $ref: '../param/filter.yml#/Filter'
  responses:
    '200':
      description: The operation was success
      content:
        application/json:
          schema:
            allOf:
              - $ref: '../component/page.yml#/Page'
              - type: object
                properties:
                  content:
                    type: array
                    items:
                      $ref: '../model/project.yml#/ProjectDto'
    '400':
      description: The operation was failed
      content:
        application/json:
          schema:
            $ref: '../component/error.yml#/ErrorResponse'
post:
  summary: Create a project
  operationId: createProject
  security:
    - bearerAuth: []
  requestBody:
    description: Project to create
    required: true
    content:
      application/json:
        schema:
          $ref: '../model/project.yml#/ProjectDto'
  responses:
    '200':
      description: The operation was success
      content:
        application/json:
          schema:
            $ref: '../model/project.yml#/ProjectDto'
    '400':
      description: The operation was failed
      content:
        application/json:
          schema:
            $ref: '../component/error.yml#/ErrorResponse'