ProjectDto:
  type: object
  properties:
    projectId:
      type: integer
      format: int64
    projectCategoryId:
      type: integer
      format: int64
    clientId:
      type: integer
      format: int64
    title:
      type: string
    description:
      type: string
    status:
      type: string
      enum: [OPEN, IN_PROGRESS, TERMINATED, FINISHED]
    activeProposalId:
      type: integer
      format: int64
    isVisible:
      type: boolean
    createdAt:
      type: string
      format: date-time
    updatedAt:
      type: string
      format: date-time