ProjectDto:
  type: object
  properties:
    projectId:
      type: integer
      format: int64
    projectCategoryId:
      type: integer
      format: int64
    client:
      $ref: 'account-response.yml#/AccountResponseDto'
    staffId:
      type: integer
      format: int64
    proposalCount:
      type: integer
      format: int32
    estimateBudget:
      type: number
      format: double
    milestones:
      type: array
      items:
        $ref: 'milestone.yml#/MilestoneDto'
    files:
      type: array
      items:
        $ref: 'file.yml#/FileDto'
    title:
      type: string
    description:
      type: string
    requiredSkills:
      type: array
      items:
        $ref: 'project-skill.yml#/ProjectSkillDto'
    status:
      type: string
      enum: [OPEN, IN_PROGRESS, TERMINATED, FINISHED]
    activeProposalId:
      type: integer
      format: int64
    latestMessage:
      $ref: 'message.yml#/MessageDto'
    isVisible:
      type: boolean
    startDate:
      type: string
      format: date-time
    createdAt:
      type: string
      format: date-time
    updatedAt:
      type: string
      format: date-time