ProjectDto:
  type: object
  properties:
    projectId:
      type: integer
      format: int64
    projectCategory:
      $ref: 'project-category.yml#/ProjectCategoryDto'
    client:
      $ref: 'account.yml#/AccountDto'
    staff:
      $ref: 'account.yml#/AccountDto'
    title:
      type: string
    description:
      type: string
    status:
      $ref: 'project-status.yml#/ProjectStatusDto'
    startDate:
      type: string
      format: date-time
    minBudget:
      type: number
      format: double
    maxBudget:
      type: number
      format: double
    createdAt:
      type: string
      format: date-time
    updatedAt:
      type: string
      format: date-time
    isVisible:
      type: boolean
    reports:
      type: array
      items:
        $ref: 'report.yml#/ReportDto'
    files:
      type: array
      items:
        $ref: 'file.yml#/FileDto'
    contract:
      $ref: 'contract.yml#/ContractDto'
    milestones:
      type: array
      items:
        $ref: 'milestone.yml#/MilestoneDto'
    requiredSkills:
      type: array
      items:
        $ref: 'project-skill.yml#/ProjectSkillDto'
    proposalCount:
      type: integer
      format: int64
    latestMessage:
      $ref: 'message.yml#/MessageDto'
    terminationReason:
      $ref: 'project-termination-reason.yml#/ProjectTerminationReasonDto'
    toTerminate:
      type: boolean
